[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Deshabilita el escaneo de secretos para las claves de Firebase que son intencionalmente públicas en el cliente.
  # Netlify las detecta como secretos, pero Firebase las requiere en el lado del cliente.
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID"
